apiVersion: v2
description: Helm chart to deploy Catalog App
name: catalog-web-app-bff
version: 2.0.4
appVersion: 2.0.4
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
